site_name: TNY Robotics - Documentation
site_description: Documentation for TNY Robotics hardware and software.
site_author: TNY Robotics
site_url: https://docs.tny-robotics.com

theme:
  language: en
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Poppins
    code: Roboto Mono

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.path
    - content.code.copy
    - content.code.annotate
    - navigation.expand
    # - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tny-robotics
      name: TNY Robotics on GitHub

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


copyright: Copyright &copy; 2025 TNY Robotics

# extra:
#   alternate:
#     - name: English
#       link: /en/
#       lang: en
#     - name: Français
#       link: /fr/
#       lang: fr
