site_name: TNY Robotics - Documentation
docs_dir: src
theme:
  language: fr
  name: material
  logo: assets/icon.png
  favicon: assets/icon.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  locale: fr
  features:
    - content.code.select
    - content.code.copy
    - content.code.annotate

extra_css:
  - assets/stylesheet.css

nav:
  - Accueil: index.md
  - 'TNY - 360':
    - Programming:
      - Blocks:
        - 'Introduction': tny360/programming/blocks/intro.md
        - 'Connecting to a TNY-360': tny360/programming/blocks/connect.md
        - 'Rotating motors': tny360/programming/blocks/motors.md
      - Python:
        - 'Introduction': tny360/programming/python/intro.md
        - 'Connecting to a TNY-360': tny360/programming/python/connect.md
        - 'Rotating motors': tny360/programming/python/motors.md

plugins: 
  - search
  - glightbox
  - build_plantuml:
      render: 'server' 
      server: 'http://www.plantuml.com/plantuml' 
      output_format: 'svg'
      output_folder: 'out'
      input_folder: 'src'
      diagram_root: 'docs/diagrams'

markdown_extensions: 
  - attr_list
  - md_in_html
  - tables
  - def_list
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg